version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: cargo
    directory: /core
    schedule:
      interval: weekly
    groups:
      core-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
    groups:
      desktop-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
