-keep class * implements kotlinx.coroutines.internal.MainDispatcherFactory
-keep class com.arkivanov.decompose.extensions.compose.mainthread.SwingMainThreadChecker
-keep class io.ktor.client.engine.cio.CIOEngineContainer