blank_issues_enabled: false
contact_links:
  - name: Сообщить об уязвимости
    url: https://github.com/boolean-false/VLauncher/security/advisories/new
    about: Приватный канал для уязвимостей и раскрытых секретов
