import { useEffect, useState } from "react";

type Feedback = { id: string; kind: string; title: string; details: string; status: string };
type Request = <T>(path: string, init?: RequestInit) => Promise<T>;
const kinds = { bug: "Ошибка", improvement: "Доработка", question: "Вопрос", category: "Добавить категорию", administration: "Запрос к администрации" };
const statuses: Record<string, string> = { new: "Новое", in_progress: "В работе", planned: "Запланировано", resolved: "Решено", closed: "Закрыто" };
export function FeedbackPanel({ request, source = "launcher", appVersion = "" }: { request: Request; source?: "launcher" | "vspace"; appVersion?: string }) {
  const [items, setItems] = useState<Feedback[]>([]); const [kind, setKind] = useState<keyof typeof kinds>("bug"); const [title, setTitle] = useState(""); const [details, setDetails] = useState(""); const [selected, setSelected] = useState<Feedback | null>(null); const [reply, setReply] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = () => request<{ items: Feedback[] }>("/feedback", { cache: "no-store" }).then(value => setItems(value.items)).catch(reason => setError(String(reason)));
  useEffect(() => { void load(); }, []);
  async function submit(work: () => Promise<unknown>) { if (busy) return; setBusy(true); setError(""); setMessage(""); try { await work(); await load(); setMessage("Обращение сохранено."); } catch (reason) { setError(String(reason)); } finally { setBusy(false); } }
  return <section className="feedback-panel"><h2>Обращения</h2><p>Сообщите об ошибке, предложите доработку, задайте вопрос или попросите добавить категорию. Ответ появится здесь.</p>{error && <p className="error-notice" role="alert">{error}</p>}{message && <p role="status">{message}</p>}<form onSubmit={event => { event.preventDefault(); void submit(() => request("/feedback", { method: "POST", body: JSON.stringify({ kind, source, title, details, app_version: appVersion, request_id: crypto.randomUUID() }) }).then(() => { setTitle(""); setDetails(""); })); }}><label>Тип обращения<select value={kind} disabled={busy} onChange={event => setKind(event.target.value as keyof typeof kinds)}>{Object.entries(kinds).map(([id, label]) => <option value={id} key={id}>{label}</option>)}</select></label><label>Коротко опишите ситуацию<input required minLength={3} maxLength={160} value={title} disabled={busy} onChange={event => setTitle(event.target.value)} /></label><label>Подробности<textarea required minLength={10} maxLength={10000} value={details} disabled={busy} onChange={event => setDetails(event.target.value)} /></label><button className="primary" disabled={busy}>{busy ? "Отправляем…" : "Отправить обращение"}</button></form><h3>Мои обращения</h3>{!items.length && <p>Обращений пока нет.</p>}{items.map(item => <article className="feedback-item" key={item.id}><button type="button" onClick={() => { setSelected(item); setReply(""); }}>{kinds[item.kind as keyof typeof kinds] ?? item.kind} · {item.title}<span>{statuses[item.status] ?? item.status}</span></button></article>)}{selected && <div className="feedback-thread"><h3>{kinds[selected.kind as keyof typeof kinds]} · {selected.title}</h3><p>{selected.details}</p><button onClick={() => setSelected(null)}>Закрыть</button><label>Ответ или уточнение<textarea value={reply} disabled={busy} onChange={event => setReply(event.target.value)} /></label><button disabled={busy || reply.trim().length < 3} onClick={() => void submit(() => request(`/feedback/${selected.id}/messages`, { method: "POST", body: JSON.stringify({ body: reply }) }))}>Отправить сообщение</button></div>}</section>;
}
