import { useEffect, useState } from "react";
type Item = { id: string; kind: string; title: string; details: string; status: string; username: string };
const kinds: Record<string, string> = { bug: "Ошибка", improvement: "Доработка", question: "Вопрос", category: "Категория", administration: "Администрация" };
export function FeedbackQueue({ request, revision }: { request: <T>(path: string, init?: RequestInit) => Promise<T>; revision: number }) {
  const [items, setItems] = useState<Item[]>([]); const [selected, setSelected] = useState<Item | null>(null); const [body, setBody] = useState(""); const [status, setStatus] = useState("in_progress"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = () => request<{ items: Item[] }>("/management/feedback", { cache: "no-store" }).then(v => setItems(v.items)).catch(e => setError(String(e)));
  useEffect(() => { void load(); }, [revision]);
  const send = async () => { if (!selected || busy || body.trim().length < 3) return; setBusy(true); setError(""); try { await request(`/management/feedback/${selected.id}`, { method: "POST", body: JSON.stringify({ body, status }) }); setBody(""); setSelected(null); await load(); } catch (e) { setError(String(e)); } finally { setBusy(false); } };
  return <section className="feedback-panel"><div className="section-heading"><div><h3>Обращения пользователей</h3><p>Единая очередь ошибок, доработок, вопросов, категорий и административных запросов.</p></div><button disabled={busy} onClick={() => void load()}>Обновить</button></div>{error && <p className="error-notice" role="alert">{error}</p>}{!items.length && <p>Новых обращений нет.</p>}{items.map(item => <article className="feedback-item" key={item.id}><button type="button" onClick={() => { setSelected(item); setBody(""); }}>{kinds[item.kind] ?? item.kind} · {item.title}<span>@{item.username} · {item.status}</span></button><p>{item.details}</p></article>)}{selected && <div className="feedback-thread"><h3>{kinds[selected.kind] ?? selected.kind} · {selected.title}</h3><p>{selected.details}</p><label>Статус<select value={status} disabled={busy} onChange={e => setStatus(e.target.value)}><option value="in_progress">В работе</option><option value="planned">Запланировано</option><option value="resolved">Решено</option><option value="closed">Закрыто</option></select></label><label>Ответ<textarea value={body} disabled={busy} onChange={e => setBody(e.target.value)} /></label><div className="modal-actions"><button disabled={busy} onClick={() => setSelected(null)}>Отмена</button><button className="primary" disabled={busy || body.trim().length < 3} onClick={() => void send()}>Ответить и сохранить</button></div></div>}</section>;
}
