name: Jar

on:
  workflow_dispatch:

jobs:
  build_jar:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Run Gradle Wrapper on Windows
        if: runner.os == 'Windows'
        run: |
          git config --global core.autocrlf false
          ./gradlew.bat

      - name: Build Jar
        run: ./gradlew packageReleaseUberJarForCurrentOS

      - name: Archive Jar artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar-artifact
          path: build/compose/jars/*.jar